---
  - hosts: pc
    ignore_errors: yes
    ignore_unreachable: yes
    become: true
    tasks:
    - name: update apt repositories and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: update all apt packages
      apt: upgrade=dist force_apt_get=yes
   
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - git
        - steam
        - tmux
        - neovim

