---
  - hosts: pi3
    ignore_errors: yes
    ignore_unreachable: yes

    tasks:
    - name: update apt repositories and cache
      become: true
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: update all apt packages
      become: true
      apt: upgrade=dist force_apt_get=yes
   
    - name: Install a list of packages
      become: true
      ansible.builtin.apt:
        pkg:
        - snapd

    - name: Reboot machine and send a message
      become: true
      ansible.builtin.reboot:
        msg: "Rebooting machine in 5 seconds"
